### ISSUE TITLE
Commands in the examples ?

### ISSUE THREAD

**Issue by jaghili** [Trophime/python_magnetrun#13]
In the root directory, when I run : 

`python3 -m python_magnetrun.utils.txt2csv data/M9_2019.02.14-23_00_38.txt --list` 

I get 

`/home/jagh/codes/python_magnetrun/magnetrun-env/bin/python3: Error while finding module specification for 'python_magnetrun.utils.txt2csv' (ModuleNotFoundError: No module named 'python_magnetrun.utils')`

It seems `utils` does not exists. When I remove it and run : 

`python3 -m python_magnetrun.txt2csv data/M9_2019.02.14-23_00_38.txt --list`

I get 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jagh/codes/python_magnetrun/python_magnetrun/txt2csv.py", line 6, in <module>
    import freesteam as st
ModuleNotFoundError: No module named 'freesteam'
```

I am not sure what is `freesteam` since I cannot find it in pip.

**Comment by jaghili** [comment]
> Indeed, the README is not up-to-date. This shall be corrected by latest commit. @jaghili Can you please confirm?
> 
> ex:
> 
> ```
> python -m python_magnetrun.python_magnetrun M9_Archive_240625-1531.tdms \
>     plot --vs_time Courants_Alimentations/Courant_GR1
> ```

Not working, I think there is a typo in `plot --vs_time`. I retried with the command : 
```
python -m python_magnetrun.python_magnetrun data/M9_Archive_240509-2133.tdms --plot_vs_time Courants_Alimentations/Courant_GR1
```

using a similar tdms file (I think I don't have M9_Archive_240625-1531.tdms) and I get : 

```
file_name=data/M9_Archive_240509-2133, file_extension=.tdms
site detected: M9
MagnetRun:frontdms: data/M9_Archive_240509-2133.tdms
group: Courants_Alimentations
channel: Courant_A1
channel: Courant_A2
channel: Courant_A3
channel: Courant_A4
channel: Référence_A1
channel: Référence_A2
channel: Référence_A3
channel: Référence_A4
channel: Courant_GR1
channel: Courant_GR2
channel: Champ_magn
group: Tensions_Alimentations
channel: Tension_A1
channel: Tension_A2
channel: Tension_A3
channel: Tension_A4
group: Tensions_Aimant
channel: Interne1
channel: Interne2
channel: Interne3
channel: Interne4
channel: Interne5
channel: Interne6
channel: Interne7
channel: Externe1
channel: Externe2
channel: ALL_internes
channel: ALL_externes
group: Tensions_MC1
channel: Tension_P_A1
channel: Tension_P_A2
channel: Tension_N_A1
channel: Tension_N_A2
group: Tensions_MC2
channel: Tension_P_A3
channel: Tension_P_A4
channel: Tension_N_A3
channel: Tension_N_A4
group: Courants_ponts
channel: A1_p1
channel: A1_p2
channel: A1_p3
channel: A1_p4
channel: A2_p1
channel: A2_p2
channel: A2_p3
channel: A2_p4
channel: A3_p1
channel: A3_p2
channel: A3_p3
channel: A3_p4
channel: A4_p1
channel: A4_p2
channel: A4_p3
channel: A4_p4
channel: Courant_A1_ponts
channel: Courant_A2_ponts
channel: Courant_A3_ponts
channel: Courant_A4_ponts
group: Haute_Tension
channel: HT2_R
channel: HT2_S
channel: HT2_T
channel: HT1_R
channel: HT1_S
channel: HT1_T
group: HT_Courant
channel: HT2_RC
channel: HT2_SC
channel: HT2_TC
channel: HT1_RC
channel: HT1_SC
channel: HT1_TC
magnetdata/fromtdms: Groups={'Courant_A1': 'Courants_Alimentations', 'Courant_A2': 'Courants_Alimentations', 'Courant_A3': 'Courants_Alimentations', 'Courant_A4': 'Courants_Alimentations', 'Référence_A1': 'Courants_Alimentations', 'Référence_A2': 'Courants_Alimentations', 'Référence_A3': 'Courants_Alimentations', 'Référence_A4': 'Courants_Alimentations', 'Courant_GR1': 'Courants_Alimentations', 'Courant_GR2': 'Courants_Alimentations', 'Champ_magn': 'Courants_Alimentations', 'Tension_A1': 'Tensions_Alimentations', 'Tension_A2': 'Tensions_Alimentations', 'Tension_A3': 'Tensions_Alimentations', 'Tension_A4': 'Tensions_Alimentations', 'Interne1': 'Tensions_Aimant', 'Interne2': 'Tensions_Aimant', 'Interne3': 'Tensions_Aimant', 'Interne4': 'Tensions_Aimant', 'Interne5': 'Tensions_Aimant', 'Interne6': 'Tensions_Aimant', 'Interne7': 'Tensions_Aimant', 'Externe1': 'Tensions_Aimant', 'Externe2': 'Tensions_Aimant', 'ALL_internes': 'Tensions_Aimant', 'ALL_externes': 'Tensions_Aimant', 'Tension_P_A1': 'Tensions_MC1', 'Tension_P_A2': 'Tensions_MC1', 'Tension_N_A1': 'Tensions_MC1', 'Tension_N_A2': 'Tensions_MC1', 'Tension_P_A3': 'Tensions_MC2', 'Tension_P_A4': 'Tensions_MC2', 'Tension_N_A3': 'Tensions_MC2', 'Tension_N_A4': 'Tensions_MC2', 'A1_p1': 'Courants_ponts', 'A1_p2': 'Courants_ponts', 'A1_p3': 'Courants_ponts', 'A1_p4': 'Courants_ponts', 'A2_p1': 'Courants_ponts', 'A2_p2': 'Courants_ponts', 'A2_p3': 'Courants_ponts', 'A2_p4': 'Courants_ponts', 'A3_p1': 'Courants_ponts', 'A3_p2': 'Courants_ponts', 'A3_p3': 'Courants_ponts', 'A3_p4': 'Courants_ponts', 'A4_p1': 'Courants_ponts', 'A4_p2': 'Courants_ponts', 'A4_p3': 'Courants_ponts', 'A4_p4': 'Courants_ponts', 'Courant_A1_ponts': 'Courants_ponts', 'Courant_A2_ponts': 'Courants_ponts', 'Courant_A3_ponts': 'Courants_ponts', 'Courant_A4_ponts': 'Courants_ponts', 'HT2_R': 'Haute_Tension', 'HT2_S': 'Haute_Tension', 'HT2_T': 'Haute_Tension', 'HT1_R': 'Haute_Tension', 'HT1_S': 'Haute_Tension', 'HT1_T': 'Haute_Tension', 'HT2_RC': 'HT_Courant', 'HT2_SC': 'HT_Courant', 'HT2_TC': 'HT_Courant', 'HT1_RC': 'HT_Courant', 'HT1_SC': 'HT_Courant', 'HT1_TC': 'HT_Courant'}
items=['Courants_Alimentations/Courant_GR1']
plot key=Courants_Alimentations/Courant_GR1, type=<class 'str'>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jagh/codes/python_magnetrun/python_magnetrun/python_magnetrun.py", line 460, in <module>
    mrun.getMData().plotData(x='Time', y=key, ax=my_ax)
  File "/home/jagh/codes/python_magnetrun/python_magnetrun/magnetdata.py", line 334, in plotData
    raise Exception("%s.%s: no y=%s key" % (self.__class__.__name__, sys._getframe().f_code.co_name, y) )
Exception: MagnetData.plotData: no y=Courants_Alimentations/Courant_GR1 key
```

I guess i am trying to plot the wrong things ?
